### PR TITLE
Fix app's state update and add exchange creation

### LINKED ISSUE #6: App isn't updating after opening a package

### PR DESCRIPTION
**Pull request by mrti259**

### CODE REVIEW

File: src/routes/album/+page.svelte [hunk 1]
```diff
@@ -1,6 +1,15 @@
...
+
+	onMount(async () => {
+		const web3Services = Web3Service.getInstance();
+		stickers = await web3Services.getStickers();
+	});
 </script>
 
 <h1>Album</h1>
-<DisplayStickersContainer max={100} />
+<DisplayStickersContainer {stickers} />
```
Comment (mrti259) [inline src/routes/album/+page.svelte:15]: Remove and get stickers from state

File: src/routes/album/+page.svelte [hunk 2]
```diff
@@ -1,6 +1,15 @@
-<script>
+<script lang="ts">
 	import DisplayStickersContainer from '$lib/components/stickers/DisplayStickersContainer.svelte';
+	import { Web3Service } from '$lib/Web3Service';
+	import { onMount } from 'svelte';
+
+	let stickers: number[] = [];
+
+	onMount(async () => {
```
Comment (mrti259) [inline src/routes/album/+page.svelte]: Remove and get data from state
